language: python

cache: pip

matrix:
    include:
        - os: linux
          python: 2.7
          sudo: required
          env: TOXENV=py27

        - os: linux
          python: 3.4
          sudo: required
          env: TOXENV=py34

        - os: linux
          python: 3.5
          sudo: required
          env: TOXENV=py35

        - os: linux
          python: 3.6
          sudo: required
          env: TOXENV=py36

        - os: linux
          dist: xenial
          python: 3.7
          sudo: required
          env: TOXENV=py37

        - os: linux
          python: 3.6
          env: TOXENV=cov
          after_success:
              - travis_retry pip install pytest-cov coveralls --upgrade
              - python setup.py test --addopts "-v --cov humanreadable --cov-report term-missing"
              - coveralls

        - os: osx
          language: generic
          env: TOXENV=py36

install:
    - travis_retry bash -x .travis/install.sh

script:
    - bash -x .travis/run_test.sh
