language: python

cache: pip

matrix:
    include:
        - os: linux
          python: 2.7
          sudo: required
          env: TOXENV=py27

        - os: linux
          python: 3.5
          sudo: required
          env: TOXENV=py35

        - os: linux
          python: 3.6
          sudo: required
          env: TOXENV=py36

        - os: linux
          dist: xenial
          python: 3.7
          sudo: required
          env: TOXENV=py37

        - os: linux
          python: 3.6
          env: TOXENV=cov
          after_success:
              - travis_retry pip install pytest-cov coveralls --upgrade
              - python setup.py test --addopts "-v --cov humanreadable --cov-report term-missing"
              - coveralls

        - os: osx
          language: generic
          env: TOXENV=py36

install:
    - travis_retry bash -x .travis/install.sh

script:
    - bash -x .travis/run_test.sh

notifications:
  slack:
    secure: WsDltr4mPYCkcZHOaXqyBOwcp17SCHONLnPn+iXXZsVW7w0quQB78EMo47AhH7SCkmn37IN464XjW8KgDMdizfoKPXCBqTBFtMvdbkf35dUn8WmCOCyQHf8SKJjljI9CREd8BE6s7kct7hhMhajV0tG+u9ojUM0BNk7GR1wR/ha6gCvQoWFBEVJGuPA4sNfHvPdcuKqiedibnXfFXHSMdzfmh3h2fJesDnZAPrwEGFQMms6BP+V4L2VA331ZXfyF58NbwwF4IvC3YsUb8YhbeOHaRQioJShhNAxeupk0jIH41Z50mGY0gVg3XayRGm5Wni3nSIGrJorHFM77PyhEOtJT9M7DiWdFMn+Vi120Xt93zWE+9b+gbVN+fh7wgEswOS6Za2RC/XFfNvKfMz6S8gqfmGThmOIBLgBM+Z837cyUubpeLpDh9URD3MRJNvgtcs03s3+06/yt5cGrK59h4PW8IE3zbzOxnkfo0+YEDhEkLwnd2ImGVCyGQn5qpjfDgr2i/Uem3+xDRAEM8cVvlyQm+EqRjSjw2l+5rjsbu9ntG/1jFKX9U8Q8Ijd7KYK5awod56xA0XoC4+j543PXWhOFCuiRug32yKyY0VVXPwVdiXwrG28QwPYiAdk3tb0/XpLcwDmcwl+qh81EyM9bYmj6QRn5+IYk1ZFAomaLcR0=
